### ISSUE TITLE
Issue #5: Navbar size and logo fix

### ISSUE THREAD

**Issue by MoNakouzi** [PACS-TMU/usstm-website#14]
**Issues:**
1- The navbar currently resizes according to the items within it. It's currently too big (along the y-axis, it spans more than it should). It is likely that the cause of this issue is the USSTM logo png (the logo has too much blank space around it). One way to check that is to use the inspect in chrome and hover over the items in the navbar.
2- The responsiveness of the navbar is not very good. The items break into a new line before the hamburger menu is automatically generated.

**To Do:**
- Create a new branch from this issue called `feature/edit-navbar`
- Find the cause of the size issue (could be either tailwind css code, the logo mentioned previously, or something else). The navbar code is currently in the file `components/header.html`.
- Fix the sizing issue of the navbar (if the image is the issue, it might need to be cropped and reuploaded. If that's the case, please ensure that minimum-to-no quality is lost).
- Add better responsiveness to the navbar. This could entail making the font size smaller on medium-sized screens, removing the `USSTM` text on smaller screens (preferred), and making the hamburger menu show on slightly larger displays than is currently assigned.

**Notes:**
- Do not edit the `<a>` tags in the navbar. Another contributor is assigned that ticket, and it may lead to merge conflicts if that is done.
- The CSS added/removed could be both regular CSS or tailwind CSS. You need an understanding of tailwind to understand why the navbar looks like it currently does, but any changes can be made using pure CSS and removing some tailwind classes.
- For both issues, you have complete freedom on how to handle it, as long as the final product is functional and does not have the same issues. Everything mentioned above is just a suggestion.
- For questions or if you face any problems, respond to this thread or reach out on the server.

**Comment by Marky301** [comment]
- The sizing issue (along the y-axis) had nothing to do with the actual size of the image. The padding attached to the first <nav> tag and all children within it made it expand. 

- To fix responsiveness, a breakpoint was added at the moment when navbar elements break into a newline, hiding the inner <nav> and displaying the hamburger menu.

**Comment by MoNakouzi** [comment]
Great work, thank you!

**Comment by MoNakouzi** [comment]
Hello @Marky301, can you please create a pull request from your branch to dev so you are added as a contributor to this project. We already migrated your implementation to next, however, to maintain your contribution please create and merge a pull request to the dev branch (which we will approve).
