### ISSUE TITLE
Issue #7: Overlay Parallax

### ISSUE THREAD

**Issue by MoNakouzi** [PACS-TMU/usstm-website#17]
**Issue:**
For the parallax image, there is no overlay for the text to go over.

**To Do:**
Create a branch called `feature/overlay`. In the branch, create an overlay over the parallax, and add USSTM over it.

**Comment by williamKhine** [comment]
I looked into it. I can see the parallax text. But I don't know what do meant by overlay. We will discuss when we meet today in person.
