### ISSUE TITLE
Issue #10: Website Design - Figma

### ISSUE THREAD

**Issue by MoNakouzi** [PACS-TMU/usstm-website#22]
**Issue:**
Familiarize yourself with Figma and how it's used for website designs.

**To Do:**

Create a free [Figma](https://www.figma.com/) account and explore the platform.
After you familiarize yourself with Figma, please respond this thread with what you think of the platform and whether our website designs should be done using it or you think we should look for alternatives.
Create a digital design for the home page. The current homepage design is sketched. Please reach out to your team lead/William to receive it. You have complete creative freedom to change the sketch as long as design fits the standards defined by USSTM. Once done design, please respond to this thread.
Homepage Details:
The homepage should include the following (some are already in sketch, please add whatever is not in sketch)

What is USSTM
Pillars
Equity / Land Acknowledgement
FAQ
No content needs to be filled, we just need a general design.

**Comment by krystalZin** [comment]
Figma is a really good platform for creating web designs. Anyone can easily learn how to use it by watching YouTube tutorials. We should definitely stick with Figma for our web designs. 
Please give me more time next time.

![USSTM](https://github.com/PACS-TMU/usstm-website/assets/128641611/e0e04b62-a21f-4539-944f-5ba229f5d212)
