### ISSUE TITLE
Issue #9: Governance Page Website Design - Figma

### ISSUE THREAD

**Issue by williamKhine** [PACS-TMU/usstm-website#23]
**Issue:**
Familiarize yourself with Figma and how it's used for website designs.

**To Do:**
Design the page `/about/governance`. Please refer to the corresponding page in the rssonline website. Keep the navbar and footer. You can reuse components from rss or you can make your own components. It is preferred that you redesign so that it looks better. You have full creative freedom.

Respond to this issue with your thoughts on Figma for website design as well as the final design of the page.

**Comment by smmgomes** [comment]
https://www.figma.com/file/L603rsVqo2UHtItR3hae25/Governance?type=design&node-id=0-1&mode=design&t=T2bwZGRRYweNqg3q-0

**Comment by MoNakouzi** [comment]
@smmgomes Thank you for creating the design! Can you please provide view access to everyone with the link so everyone is able to see it?

**Comment by smmgomes** [comment]
Sure will! I’m not home right now, but I’ll be sure to do it by tonight
(your morning).
