### ISSUE TITLE
Issue #12: Elections Page Website Election Page - Figma

### ISSUE THREAD

**Issue by MoNakouzi** [PACS-TMU/usstm-website#28]
**Issue:**
In the current website, the [elections page](https://www.rssonline.ca/about/elections/) is very disorganized and hard to read.

**To Do:**

- Create a free [Figma](https://www.figma.com/) account and explore the platform.
- After you familiarize yourself with Figma, please respond this thread with what you think of the platform and whether our website designs should be done using it or you think we should look for alternatives.
- Create a design for the election page. You have full creative freedom of what to use and how to organize the information. The information on the current website might be a bit outdated, but it should provide the gist of what this page is expected to hold.

Note: Please stick to the color scheme when designing this page. This is constantly changing, but it is currently a white background, black text, and the highlights we use are the blue that USSTM usually uses (mainly on their Instagram page). For exact hex codes of the blue we're currently using, please reach out to Mo/William, however feel free to experiment with similar shades and suggest them as the highlights of the webpage, as we are unable of finding a highlighting color that pleases everyone.

**Comment by smmgomes** [comment]
Got it! I’ll start working on it.

**Comment by bensonzhang04** [comment]
@smmgomes sorry for the miscommunication, please refer to [this doc](https://docs.google.com/document/d/1mZLt3micZJoOIMg9VY2Gd4nyf2cqHm8ZtZcOYL6j8Xg/edit?usp=sharing) for the election info. this should not happen again.

design-wise, it looks very good! just update the content/headers to match the doc and remove that calender that is currently on the design

p.s moving forward please use the github comment section instead.

**Comment by MoNakouzi** [comment]
Adding <a href="https://www.figma.com/file/NtHZM4nIDZTxpeD5RefrTg/Election?type=design&node-id=0-1&mode=design&t=jdKN7UievSNtQFIh-0" target="_blank">Figma</a> link for visibility.

**Comment by MoNakouzi** [comment]
Thank you for all the hard work!
