### ISSUE TITLE
Creating the "Meet Your Team" Page

### ISSUE THREAD

**Issue by MoNakouzi** [PACS-TMU/usstm-website#36]
- Create a new branch called `feature/meet-team` (you can follow the [GitHub docs](https://github.com/PACS-TMU/documentation/blob/main/github-docs.md) to create a branch or create it from this issue).

- In your branch, create the "Meet Your Team" page. This page will be very similar to the [TRSS Society's Meet The Team Page](https://www.trssociety.ca/our-team-link).

- To create this page you need to edit the `page.jsx` file under `src/about/your-team/page.jsx`.

- Ensure you stick to the color scheme of the website; use tailwind/CSS variables whenever possible.

- Pictures for this page will be taken on January 8th, 2023. This is after this ticket is due, therefore, you can use placeholders for the images for the time being.

- There should be buttons below each group image to redirect to the committees, similar to the TRSS website.

- For this ticket, just create the following entry:
    - Board of Directors -> should redirect to `/about/your-team/directors`
 
Create the heading of the page, the board of directors heading, the image as a place holder (implement a carousel if possible), a short description placeholder, and finally a button. Again, this will look very similar to the TRSS design.

Finally, if you add any external libraries to use in your implementation, please ask in this thread before you do it. The project lead will have to decide whether the library is necessary and whether there are better alternatives (potentially already installed).

> [!TIP]
> This ticket is assigned to 2 people. To ensure success, practice effective communication and teamwork, and split the work evenly according to your skill sets.

> [!NOTE]
> Please notify if you want to install new npm packages so that we can keep track.
> If you face any issues, please raise them here on this thread, however small. Communication is key, please make sure to keep us updated on your ticket and on any questions you have.
> This ticket is due on December 29th, 2023 (as per the milestone)

**Comment by Marky301** [comment]
@CodingMaster745 I don't know your username on Discord, so please reach out to me so we can discuss how to go about this together. 

Discord ID: markymarkmarker

**Comment by bensonzhang04** [comment]
@Marky301 @CodingMaster745 photos for the meet the team page will be taken on Jan 8th. Would you guys prefer us to have multiple photos for each committee (like how TRSS does it) and have a carousel or would you like one photo per committee?

**Comment by Marky301** [comment]
> @Marky301 @CodingMaster745 photos for the meet the team page will be taken on Jan 8th. Would you guys prefer us to have multiple photos for each committee (like how TRSS does it) and have a carousel or would you like one photo per committee?

Currently, we have implemented a carousel. Multiple photos is probably the best
