### ISSUE TITLE
Data Structure for Past Board

### ISSUE THREAD

**Issue by williamKhine** [PACS-TMU/usstm-website#37]
Create a new branch `/feature/past-board-structure` for this issue.

In the `/public/data/` directory, touch (create) a new JSON file called `past-boards.json` and create a data structure that is suitable to be rendered in the website using React. Reference the two other JSON files already created in the same directory. Also reference how we fetched the data in the components `navbar.jsx` and `faq.jsx`.

Start by creating an array of JS objects, and in each object should contain an id (come up with a suitable id convention), year (the year they were in power), and an array of objects of the board members which has an id (also come up with a suitable id convention), name, position.

Place placeholders or dummy data in the JSON and render it in the `past-boards` page. Does not need to look good, it's okay if the data shows up in a readable format.

Create a pull request with a description of what and how you coded this task.

If you have any questions you can comment on this issue or message me on discord @yumicol.

> [!TIP]
> This ticket is assigned to 2 people. To ensure success, practice effective communication and teamwork, and split the work evenly according to your skill sets.

> [!NOTE]
> Please notify if you want to install new npm packages so that we can keep track.
> This ticket is due on December 29th, 2023 (as per the milestone).

**Comment by MoNakouzi** [comment]
It should look something like [this](https://docs.google.com/document/d/1RmiuM7h70lyJcrIQBhc5UAzpuFpwPy1-gPjhlg26tKU/edit), without any proper design being integrated

**Comment by MoNakouzi** [comment]
@andrearcaina, can you please update the IDs in the json file to include the years? For example, 
"id": "board" should be "id": "board-22", "id": "executives" should be "id": "executives-22". This would allow us to keep track and add more past boards in the future.

As for the visual implementation, it looks good, but there is a lot of wasted space to the right of each entry. Would it be possible to display them as a responsive grid in order to make better use of space? Let me know your thoughts

**Comment by andrearcaina** [comment]
@MoNakouzi Will do! I whipped up the CSS without much thought but its definitely possible. I will start doing that as soon as I can.

As for the ID, I didn't know what to do, but adding the year after each of them makes sense!

**Comment by bensonzhang04** [comment]
@andrearcaina heads up, i changed up the structure of past-boards.json a bit. nothing major and nothing breaks your code!

**Comment by andrearcaina** [comment]
@bensonzhang04 Per your request, I have changed the people list as a list of names instead of a list of objects with certain ID's and positions, and have rendered it to the page. 

Let me know if it looks good 👍
