### ISSUE TITLE
Missing Hovering in Navbar Sub elements

### ISSUE THREAD

**Issue by callmeVineeth** [PACS-TMU/usstm-website#46]
![Screenshot (207)](https://github.com/PACS-TMU/usstm-website/assets/130293688/d0373fc6-3452-4c85-bcd2-745c0e6a7ff0)
It will  look better if given some hovering to Subtitles of Navbar elements. Also there are lot of 'temp' words  exist.

**Comment by callmeVineeth** [comment]
Please Assign this task to me I would like to work on this  issue. I will also remove 'temp' and add some one line descriptions in its place.

**Comment by MoNakouzi** [comment]
@callmeVineeth, I will assign this ticket to you. Please create a branch called `feature/nav-hover` and make your changes there, and create a pull request to dev for review. If possible, please look into the responsiveness and smaller screen design as well, and see if there are any design changes you'd like to suggest.

**Comment by callmeVineeth** [comment]
Thanks for assigning the task to me . I will consider the responsiveness part for sure.

**Comment by MoNakouzi** [comment]
Any updates on this ticket?
