### ISSUE TITLE
Create the `/finance` page

### ISSUE THREAD

**Issue by williamKhine** [PACS-TMU/usstm-website#65]
You have full creative freedom to design and build this page. Make sure it is visually pleasing though.

The contents should be links that will redirect clients to the sub items according to the path. Reference the `public/data/nav-items.json` file to fetch the data and render it on the page.

Do this in a new branch and submit a PR to the `dev` branch.

Reference issue #64 and work with its assignee (@syxddd10001) to make the design consistent.

> [!NOTE]
> This page will not be linked by other pages on the website and can be only accessed by manually typing in the path in the URL.

**Comment by andrearcaina** [comment]
@syxddd10001 Let me know if it looks good, otherwise I'll change it to whatever you have

**Comment by syxddd10001** [comment]
This looks good to me @andrearcaina
